// Package client provides a typed Go client for all Polymarket gRPC services.
// Use this in CLI tools, integration tests, or other microservices.
package client

import (
	"context"
	"fmt"
	"time"

	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/metadata"

	"github.com/polymarket-grpc/models"
	mktSvc "github.com/polymarket-grpc/services/market"
	ordSvc "github.com/polymarket-grpc/services/order"
	usrSvc "github.com/polymarket-grpc/services/user"
	walSvc "github.com/polymarket-grpc/services/wallet"
)

// PolyClient is a single client that connects to all Polymarket services.
// When connecting to a real gRPC server you would swap the in-process
// calls for real gRPC stub calls generated by protoc.
type PolyClient struct {
	userSvc   *usrSvc.Server
	marketSvc *mktSvc.Server
	orderSvc  *ordSvc.Server
	walletSvc *walSvc.Server
	token     string
	logger    *zap.Logger
}

// NewPolyClient creates a client pointing at the given gRPC address.
// In this project we accept the concrete service servers directly so that
// the code can be demonstrated without a running network server.
func NewPolyClient(
	userSvr *usrSvc.Server,
	marketSvr *mktSvc.Server,
	orderSvr *ordSvc.Server,
	walletSvr *walSvc.Server,
	logger *zap.Logger,
) *PolyClient {
	return &PolyClient{
		userSvc:   userSvr,
		marketSvc: marketSvr,
		orderSvc:  orderSvr,
		walletSvc: walletSvr,
		logger:    logger,
	}
}

// NewGRPCConn is a helper that establishes a plain-text gRPC connection.
// Use this when talking to a real remote gRPC server.
func NewGRPCConn(addr string) (*grpc.ClientConn, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	conn, err := grpc.DialContext(
		ctx,
		addr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithBlock(),
	)
	if err != nil {
		return nil, fmt.Errorf("dial %s: %w", addr, err)
	}
	return conn, nil
}

// SetToken stores a bearer token that will be attached to every request.
func (c *PolyClient) SetToken(token string) {
	c.token = token
}

// ctx returns a context enriched with the stored bearer token as
// gRPC metadata, so that the server-side auth interceptors pass.
func (c *PolyClient) ctx() context.Context {
	if c.token == "" {
		return context.Background()
	}
	md := metadata.New(map[string]string{
		"authorization": "Bearer " + c.token,
	})
	return metadata.NewIncomingContext(context.Background(), md)
}

// ============================================================
//  User Operations
// ============================================================

func (c *PolyClient) Register(username, email, password, wallet string) (*usrSvc.CreateUserResponse, error) {
	return c.userSvc.CreateUser(context.Background(), &usrSvc.CreateUserRequest{
		Username:      username,
		Email:         email,
		Password:      password,
		WalletAddress: wallet,
	})
}

func (c *PolyClient) Login(email, password string) (*usrSvc.AuthenticateResponse, error) {
	resp, err := c.userSvc.Authenticate(context.Background(), &usrSvc.AuthenticateRequest{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return nil, err
	}
	c.SetToken(resp.Token)
	return resp, nil
}

func (c *PolyClient) GetUser(id string) (*usrSvc.GetUserResponse, error) {
	return c.userSvc.GetUser(c.ctx(), &usrSvc.GetUserRequest{ID: id})
}

// ============================================================
//  Market Operations
// ============================================================

func (c *PolyClient) ListMarkets(category string, page, perPage int) (*mktSvc.ListMarketsResponse, error) {
	return c.marketSvc.ListMarkets(c.ctx(), &mktSvc.ListMarketsRequest{
		Category: category,
		Page:     page,
		PerPage:  perPage,
	})
}

func (c *PolyClient) GetMarket(id string) (*mktSvc.GetMarketResponse, error) {
	return c.marketSvc.GetMarket(c.ctx(), &mktSvc.GetMarketRequest{ID: id})
}

func (c *PolyClient) CreateMarket(
	title, description, category, resolution string,
	endTime time.Time,
	tags []string,
	liquidity float64,
) (*mktSvc.CreateMarketResponse, error) {
	return c.marketSvc.CreateMarket(c.ctx(), &mktSvc.CreateMarketRequest{
		Title:            title,
		Description:      description,
		Category:         category,
		ResolutionSource: resolution,
		EndTime:          endTime,
		Tags:             tags,
		InitialLiquidity: liquidity,
	})
}

// ============================================================
//  Order Operations
// ============================================================

func (c *PolyClient) BuyYes(marketID string, amount, price float64) (*ordSvc.PlaceOrderResponse, error) {
	return c.orderSvc.PlaceOrder(c.ctx(), &ordSvc.PlaceOrderRequest{
		MarketID: marketID,
		Side:     models.OrderSideBuy,
		Type:     models.OrderTypeLimit,
		Amount:   amount,
		Price:    price,
		Outcome:  models.MarketOutcomeYes,
	})
}

func (c *PolyClient) BuyNo(marketID string, amount, price float64) (*ordSvc.PlaceOrderResponse, error) {
	return c.orderSvc.PlaceOrder(c.ctx(), &ordSvc.PlaceOrderRequest{
		MarketID: marketID,
		Side:     models.OrderSideBuy,
		Type:     models.OrderTypeLimit,
		Amount:   amount,
		Price:    price,
		Outcome:  models.MarketOutcomeNo,
	})
}

func (c *PolyClient) SellPosition(marketID string, amount, price float64, outcome models.MarketOutcome) (*ordSvc.PlaceOrderResponse, error) {
	return c.orderSvc.PlaceOrder(c.ctx(), &ordSvc.PlaceOrderRequest{
		MarketID: marketID,
		Side:     models.OrderSideSell,
		Type:     models.OrderTypeLimit,
		Amount:   amount,
		Price:    price,
		Outcome:  outcome,
	})
}

func (c *PolyClient) CancelOrder(orderID string) (*ordSvc.CancelOrderResponse, error) {
	return c.orderSvc.CancelOrder(c.ctx(), &ordSvc.CancelOrderRequest{OrderID: orderID})
}

func (c *PolyClient) GetOrderBook(marketID string) (*ordSvc.OrderBookProto, error) {
	return c.orderSvc.GetOrderBook(c.ctx(), &ordSvc.GetOrderBookRequest{MarketID: marketID})
}

func (c *PolyClient) ListMyOrders(page, perPage int) (*ordSvc.ListOrdersResponse, error) {
	return c.orderSvc.ListOrders(c.ctx(), &ordSvc.ListOrdersRequest{
		Page:    page,
		PerPage: perPage,
	})
}

// ============================================================
//  Wallet Operations
// ============================================================

func (c *PolyClient) GetWallet() (*walSvc.GetWalletResponse, error) {
	return c.walletSvc.GetWallet(c.ctx(), &walSvc.GetWalletRequest{})
}

func (c *PolyClient) Deposit(amount float64, reference string) (*walSvc.DepositResponse, error) {
	return c.walletSvc.Deposit(c.ctx(), &walSvc.DepositRequest{
		Amount:    amount,
		Reference: reference,
	})
}

func (c *PolyClient) Withdraw(amount float64, address string) (*walSvc.WithdrawResponse, error) {
	return c.walletSvc.Withdraw(c.ctx(), &walSvc.WithdrawRequest{
		Amount:  amount,
		Address: address,
	})
}

func (c *PolyClient) ListTransactions(page, perPage int) (*walSvc.ListTransactionsResponse, error) {
	return c.walletSvc.ListTransactions(c.ctx(), &walSvc.ListTransactionsRequest{
		Page:    page,
		PerPage: perPage,
	})
}

// ============================================================
//  Example end-to-end workflow
// ============================================================

// RunE2EWorkflow is a self-contained demo that exercises the full system.
func RunE2EWorkflow(c *PolyClient, logger *zap.Logger) error {
	logger.Info("=== Starting E2E Workflow ===")

	// 1. Register
	regResp, err := c.Register("alice", "alice@example.com", "Password123!", "0xALICE")
	if err != nil {
		return fmt.Errorf("register: %w", err)
	}
	logger.Info("registered", zap.String("user_id", regResp.User.ID))
	c.SetToken(regResp.Token)

	// 2. Deposit funds
	depResp, err := c.Deposit(5000, "initial-deposit-001")
	if err != nil {
		return fmt.Errorf("deposit: %w", err)
	}
	logger.Info("deposited", zap.Float64("balance", depResp.Wallet.Balance))

	// 3. List markets
	mkts, err := c.ListMarkets("", 1, 10)
	if err != nil {
		return fmt.Errorf("list markets: %w", err)
	}
	if len(mkts.Markets) == 0 {
		return fmt.Errorf("no markets found")
	}
	firstMarket := mkts.Markets[0]
	logger.Info("found market",
		zap.String("title", firstMarket.Title),
		zap.Float64("yes_prob", firstMarket.YesProbability),
	)

	// 4. Place a BUY YES order
	orderResp, err := c.BuyYes(firstMarket.ID, 100.0, 0.65)
	if err != nil {
		return fmt.Errorf("buy yes: %w", err)
	}
	logger.Info("placed order",
		zap.String("order_id", orderResp.Order.ID),
		zap.String("status", string(orderResp.Order.Status)),
	)

	// 5. Check order book
	book, err := c.GetOrderBook(firstMarket.ID)
	if err != nil {
		return fmt.Errorf("order book: %w", err)
	}
	logger.Info("order book",
		zap.Int("bids", len(book.Bids)),
		zap.Int("asks", len(book.Asks)),
	)

	// 6. Check wallet balance
	walletResp, err := c.GetWallet()
	if err != nil {
		return fmt.Errorf("get wallet: %w", err)
	}
	logger.Info("wallet balance",
		zap.Float64("balance", walletResp.Wallet.Balance),
		zap.Float64("locked", walletResp.Wallet.LockedBalance),
	)

	logger.Info("=== E2E Workflow Complete ===")
	return nil
}
